### PR TITLE
Updated migration to resolve integrity error

### PR DESCRIPTION
**Pull request by iamsobanjaved**
**Description:** Describe in a couple of sentences what this PR adds

**JIRA:** Link to JIRA ticket

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPI after tag-triggered build is 
      finished.
- [ ] Delete working branch (if not needed anymore)

### CODE REVIEW

**Comment by iamsobanjaved** [comment]
@jmbowman even after changing the order according to the table relations, the issue didn't resolve in edx-platform. What should be the next step, revert the migration PR?

Test PR in `edx-platform`: https://github.com/edx/edx-platform/pull/26039

**Comment by jmbowman** [comment]
Yeah, let's go ahead and revert the migration.  Please create a separate ticket for removing these tables manually (which will require assistance from SRE); that ticket should also cover adding our findings on how to remove these tables to the Lilac release notes, for any Open edX installations that want to clean up the unused tables.

**Comment by jmbowman** [comment]
Is this PR still needed?

**Comment by iamsobanjaved** [comment]
Nope

**Pull request closed without merging**
